---
abstract: 'Disable illegal prototype warnings on old Perls'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: warnings-illegalproto
requires:
  Test::More: 0.92
  strictures: 1
resources:
  repository: git://github.com/frioux/warnings-illegalproto
version: 0.001001
